### ISSUE TITLE
where is face_detection_ov?

### ISSUE THREAD

**Issue by pjkasper** [odundar/face-detection-python#1]
Installed OpenVINO 2019_R2- OK in a conda environ, c++ demos work fine
But this app cannot import face_detection_ov

What am i doing wrong?

Regards
K

**Comment by bus710** [comment]
Sounds like I have a same issue.

My error log is attached below:

```
python3 face_detection_openvino.py config/config.json                               
WARNING:root:Log Level Set to: DEBUG                                                                                     
INFO:root:Setting Configurations                                                                                         
INFO:root:Loading JSON File config/config.json                                                                           
INFO:root:Model Type mtcnn_facedetection                                                                                 
INFO:root:Loading JSON File config/config.json
INFO:root:Model Type mtcnn_age_gender       
INFO:root:Setting Up R - O Network Input Storage
INFO:root:CPU Extensions Added                                                      
Traceback (most recent call last):                                                           
  File "face_detection_openvino.py", line 314, in <module>                       
    run_app()                          
  File "face_detection_openvino.py", line 78, in run_app
    face_infer = MtCNNFaceDetection(face_cfg)  
  File "/home/retail/Desktop/face-detection-python/detection/face_detection_ov.py", line 321, in __init__
    super(MtCNNFaceDetection, self).__init__(config)              
  File "/home/retail/Desktop/face-detection-python/detection/detection_base_ov.py", line 157, in __init__
    self.prepare_detector()          
  File "/home/retail/Desktop/face-detection-python/detection/face_detection_ov.py", line 341, in prepare_detector
    self.OpenVinoIE.add_extension(self.Config.CpuExtensionPath, "CPU")                    
  File "ie_api.pyx", line 118, in openvino.inference_engine.ie_api.IECore.add_extension   
RuntimeError: Cannot load library '~/inference_engine_samples_build/intel64/Release/lib/libcpu_extension.so': ~/inferenc$
_engine_samples_build/intel64/Release/lib/libcpu_extension.so: cannot open shared object file: No such file or directory
```

I am using OpenVINO 2019 R3.334 and there is no libcpu_extension.so but 3 other files that have surfix like "avx2" or so.

**Comment by bus710** [comment]
I guess that the config/config.json can be modified per each case/environment.
The path to CPU Extension Path and model of R2 and R3 are different so that it is little hard to launch the entire system.
