### ISSUE TITLE
How can I solve this `ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory`?

### ISSUE THREAD

**Issue by masouduut94** [odundar/face-detection-python#2]
This error happens everytime when I want to run the app:
Traceback (most recent call last):
  File "app/face_detection_openvino.py", line 28, in <module>
    from detection.face_detection_ov import FaceDetectionConfig, OpenMZooFaceDetection, FaceDetectionModelTypes, MtCNNFaceDetection, MTCNNFaceDetectionConfig
  File "/home/gpu/codes/MSD/openvino_face_detection/detection/face_detection_ov.py", line 31, in <module>
    from openvino.inference_engine import IENetwork, IECore, ExecutableNetwork
  File "/opt/intel/openvino_2019.3.376/python/python3.7/openvino/inference_engine/__init__.py", line 1, in <module>
    from .ie_api import *
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

I ran the program in python 3.6 and python 3.7?

**Comment by payal211** [comment]
You can specify your python_version, when you run setupvars.sh. 

l solved by simply running the setupvars.sh file using python3.5 version instead of 3.6.
source /opt/intel/openvino/bin/setupvars.sh -pyver 3.5

**Comment by avideci** [comment]
Simply `apt install python3.7-dev` and it should work.

The problem is that the .so library of python is missing form the environment - this is not OpenVino specific.
This has nothing to do with setupvars.sh.
